//: Playground - noun: a place where people can play

import UIKit

//1. Greeting
//Create a function called greeting that accepts one parameter, an array of people's names. The function should print a greeting for each name in the array. If there are more than seven people in the array, it should only print "Hi everybody!"
//greeting(["Gerry", "Terry", "Gary"])
//   prints:
//   "Hi Gerry!"
//   "Hi Terry!"
//   "Hi Gary!"

//greeting(["Gerry", "Terry", "Gary", "Amanda", "Daveon", "Benjamin", "Nick", "Nate", "Peyton"])
//   prints:
//   "Hi everyone!"



//-------------------------------------------------------------------------------------------------------------------------------
//2. Expand
//Define a function called expand that accepts a string parameter and returns a string twice as long as the argument. Each character should be accompanied by a new identical character next to it.
//print(expand("banana")) // prints "bbaannaannaa"
//print(expand("My name is Sara.")) // prints "MMyy  nnaammee  iiss SSaarraa.."






//-------------------------------------------------------------------------------------------------------------------------------
//3. Roller Coaster
//Create a function called rollerCoaster that accepts two parameters: an array of type [Double] that contains the heights people in line for a roller coaster, and a parameter of type Double that is the minimum height to ride the roller coaster. It should return an integer value representing the number of people in line who are tall enough to ride the roller coaster.
//rollerCoaster([49.5, 67.5, 80.0, 72.0, 51.5, 64.0], minHeight: 54.0) //returns 4
//rollerCoaster([68.0, 55.5, 62.0], minHeight: 54.0) //returns 3





//-------------------------------------------------------------------------------------------------------------------------------
//Bonus: Fibonacci
//In the Fibonacci sequence, each number is generated by adding together the two previous numbers. The first five terms are: 1, 2, 3, 5, 8. Write a function called fibonacci that accepts an integer parameter and returns an array of that number of elements of the fibonacci sequence.
//fibonacci(10) //returns [1, 2, 3, 5, 8, 13, 21, 34, 55, 89]